apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout
  annotations:
    github.com/project-slug: gy-org/checkout
    backstage.io/kubernetes-label-selector: 'app=checkout'
  description: checkout created
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  # dependsOn:
  #   - resource:crossplane-eks-demo-05